name: Node.js CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # Specifies the Node.js version to use.
    - name: Install dependencies
      run: npm ci # Installs project dependencies.
    - name: Run tests
      run: npm test # Executes your project's tests.
